version: 2

jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: sudo npm i -g npm
      - run:
          name: "Checking Versions"
          command: |
            node --version
            npm --version
      - run: npm install
      - run: npm run test
